### ISSUE TITLE
WiX Installer name is random

### ISSUE THREAD

**Issue by ffAudio** [AliceOh/CreateWindowsInstaller#1]
Thank you so much for this gh action. It makes life so much easier.

Unfortunately I couldn't find much information on the wix.json file, so I guess I have various things still wrong.

The screen is opened with "Do you want to allow 690bf.msi allow to make changes to your device?"

How can I make the 690bf.msi to be the actual installer name?

Thanks again

**Comment by ffAudio** [comment]
Apologies, this name is not taken from the installer at all. Turns out it was an artefact from signing the installer and not supplying a description.

**Comment by AliceOh** [comment]
Hi, Daniel,
I am glad my GitHub repo helped.

Cheers
Alice
